version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    versioning-strategy: auto

    labels:
      - 'dependencies'

    groups:
      # Security updates (all dependencies, auto-merge)
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'

      # React ecosystem (minor/patch only)
      react-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'react-*'

      # React major updates
      react-major:
        applies-to: version-updates
        update-types:
          - 'major'
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'react-*'

      # Next.js ecosystem (minor/patch only)
      next-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'next'
          - 'eslint-config-next'

      # Next.js major updates
      next-major:
        applies-to: version-updates
        update-types:
          - 'major'
        patterns:
          - 'next'
          - 'eslint-config-next'

      # Tailwind ecosystem (minor/patch only)
      tailwind-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-*'

      # Tailwind major updates
      tailwind-major:
        applies-to: version-updates
        update-types:
          - 'major'
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-*'

      # TypeScript ecosystem (minor/patch only)
      typescript-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'typescript'
          - '@types/*'
        exclude-patterns:
          - '@types/react*'

      # TypeScript major updates
      typescript-major:
        applies-to: version-updates
        update-types:
          - 'major'
        patterns:
          - 'typescript'
          - '@types/*'
        exclude-patterns:
          - '@types/react*'

      # All other minor/patch updates
      all-other-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - '*'
        exclude-patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'react-*'
          - 'next'
          - 'eslint-config-next'
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-*'
          - 'typescript'
          - '@types/*'

      # All other major updates
      all-other-major:
        applies-to: version-updates
        update-types:
          - 'major'
        patterns:
          - '*'
        exclude-patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - 'react-*'
          - 'next'
          - 'eslint-config-next'
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-*'
          - 'typescript'
          - '@types/*'

    # Commit message configuration
    commit-message:
      prefix: 'deps'
      prefix-development: 'dev-deps'
      include: 'scope'

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'automerge'
    commit-message:
      prefix: 'ci'
