version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    versioning-strategy: auto
    # Group updates by framework
    groups:
      # React ecosystem (separate from other packages)
      react-updates:
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'react'
          - 'react-*'
          - '@types/react*'
      # Next.js ecosystem (separate from other packages)
      nextjs-updates:
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - 'next'
      # All other minor/patch updates grouped together
      other-updates:
        update-types:
          - 'minor'
          - 'patch'
        patterns:
          - '*'
        exclude-patterns:
          - 'react'
          - 'react-*'
          - '@types/react*'
          - 'next'
      # Major updates kept separate for careful review
      major-updates:
        update-types:
          - 'major'
        patterns:
          - '*'
    # Labels to apply to pull requests
    labels:
      - 'dependencies'
    # Commit message configuration
    commit-message:
      prefix: 'deps'
      prefix-development: 'dev-deps'
      include: 'scope'
