version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 4
    versioning-strategy: auto

    groups:
      # React ecosystem
      react-updates:
        update-types: [minor, patch]
        patterns:
          - 'react'
          - 'react-*'
          - '@types/react*'
        labels: ['dependencies', 'react']
        schedule:
          interval: 'daily'

      # Next.js ecosystem
      nextjs-updates:
        update-types: [minor, patch]
        patterns:
          - 'next'
          - 'eslint-config-next'
        labels: ['dependencies', 'next']
        schedule:
          interval: 'daily'

      # Tailwind CSS ecosystem
      tailwind-updates:
        update-types: [minor, patch] # Only safe minor/patch updates auto-merge
        patterns:
          - 'tailwind*'
          - 'autoprefixer'
          - '@tailwindcss/*'
        labels: ['dependencies', 'tailwind', 'automerge']

      # TypeScript & @types
      typescript-updates:
        update-types: [minor, patch] # Only safe minor/patch updates auto-merge
        patterns:
          - 'typescript'
          - '@types/*'
        labels: ['dependencies', 'typescript', 'automerge']

      # Security updates
      security-updates:
        update-types: [security]
        patterns: ['*']
        labels: ['dependencies', 'security', 'automerge']

      # All other minor/patch updates
      other-updates:
        update-types: [minor, patch]
        patterns: ['*']
        labels: ['dependencies']

      # Major updates (manual review)
      major-updates:
        update-types: [major]
        patterns: ['*']
        labels: ['dependencies', 'major']

    # Commit message configuration
    commit-message:
      prefix: 'deps'
      prefix-development: 'dev-deps'
      include: 'scope'

    # Assign yourself for PR reviews
    reviewers:
      - 'davie3'

    # Always create security PRs if applicable
    security-updates: true
